### ISSUE TITLE
How to create an instance of a class?

### ISSUE THREAD

**Issue by oscardhc** [peterzheng98/Compiler-2020#28]
In `scope-6.mx` it creates with `A a = new A();`, while in `class-5.mx` it uses `Cat cat; cat = new Cat;`, and in `class-11.mx` it simply uses `A b; int c = b.a;`. All of these 3 tests are marked with 'Success' verdict.
Are these all valid statements to create an instance?

**Comment by Engineev** [comment]
@oscardhc Hello. As I understood it, all of this are valid in the _semantic_ sense. `Cat cat;` is equivalent to equivalent to `Cat cat = null;`. In the second example, though `b` is actually `null` and accessing `b.a` would raise a runtime error, it is still semantically correct. In fact, detecting `null` pointers is impossible in most languages, including Mx*. 

Also, we will not execute any sema testcase, so you don't need to worry about potential runtime error. And we have not reviewed the testcases yet. Hence, feel free to open issues if you have found other possible errors in the testcases.

**Comment by peterzheng98** [comment]
After checking the manual, `class-11.mx` will be changed since accessing object without initializing is undefined. In many languages, `NullPointerException` is runtime error. We ensure that these cases will not show in code generation test or optimization test. You can also try to output the potential runtime error as warnings. :)
