### ISSUE TITLE
questions about array construction

### ISSUE THREAD

**Issue by jinhongyii** [peterzheng98/Compiler-2020#32]
suppose A is a user-defined class
How many times will sentence A[] a = new A [10]; call constructor A() ?

**Comment by peterzheng98** [comment]
Hello! Constructor A() will be executed for 10 times. You can validate this result by executing the simple cpp code.
``````c++
#include<cstdio>

class A{
  public:
    A(){
      printf("hello\n");
    }
};

int main(){ 
  A *a = new A[10];
  return 0;
}
``````
The output is:
``````
# peterzheng @ WENXINZHENG-MB0 in ~ [18:31:14] 
$ ./a.out         
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
``````

**Comment by MasterJH5574** [comment]
Hello! In my point of view, **class in Mx\* is similar to class in Java**. If you write a Java program as below to check this question, you'll get a totally different result.

```java
class A {
    A() {
        System.out.println("Hello!");
    }
}

public class Test {
    public static void main(String[] args) {
        A[] arr = new A[10];
        System.out.println(arr[0]);
    }
}
```

The output is:

```
null
```

So...Should we follow the C convention or the Java convention?
Thank you!

**Comment by Engineev** [comment]
In my opinion, after the line `A[] a = new A[10];`, elements in `a` should be `null`, instead of being initialized using the default constructor, since we are using a java-like model in Mx* and it is more consistent with the behavior of `int[][] a = new int[10][];`.

I believe it is actually a legacy issue that default constructor should be called in `new A[10]` since some testcases written by students many years ago follow the convention that constructors should be called, and for now we don't have the time to review the testcases. 

We have not decided yet whether we should fix this issue. Maybe you could follow the Java convention, which I believe is more appropriate, and report testcases that are invalid. We will fix them by explicitly initializing the elements in a loop after `new A[10]`.

**Comment by peterzheng98** [comment]
After discussion, we think the java convention is more appropriate since our behavior when calling `new` is similar to the behavior in Java. So the answer will change to `null`. If anyone can find any test cases  like this and that test case do not call constructor,  just make a new issue freely.
